apiVersion: v1
kind: Service
metadata:
  name: weather-collector-service
  namespace: data-pipeline
spec:
  selector:
    app: weather-collector
  ports:
  - port: 50051
    targetPort: 50051
  type: ClusterIP